version: "3.9"

services:
  database:
    image: postgres:12
    container_name: database
    environment:
      - POSTGRES_PASSWORD=123123
    ports:
      - "7777:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - spring_net

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
    networks:
      - spring_net

networks:
  spring_net:
    driver: bridge 
