version: "3.9"

services:
  postgres:
    image: postgres:12
    container_name: database
    environment:
      - POSTGRES_PASSWORD=123123
    ports:
      - "7777:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - spring_net

  backend:
    build: .backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - spring_net
    depends_on:
      - postgres
